! SPDX-Identifier: MIT
module stdlib_base64
    ! 1. You must IMPORT the new subroutines from the sub-modules
    use stdlib_base64_encode, only: base64_encode, base64_encode_into
    use stdlib_base64_decode, only: base64_decode, base64_decode_into
    
    implicit none
    private

    ! 2. Now you can safely EXPORT them to the user
    public :: base64_encode, base64_encode_into
    public :: base64_decode, base64_decode_into

end module stdlib_base64